# -*- coding: utf-8 -*-
"""
E-Field Time Animation — pvpython visualisation script
Generated by Simple_Patch_Antenna_Display.py

Run in batch mode (no GUI, saves screenshots + state):
    pvpython visualize.py

Open in the ParaView GUI instead:
    paraview --script=visualize.py
"""

import os, sys
from pathlib import Path

# ── Auto-relaunch with pvpython if run under regular Python ──────────────────
try:
    from paraview import simple as pv
except ModuleNotFoundError:
    import subprocess
    PVPYTHON = Path(r'C:\Program Files\ParaView 6.1.0\bin\pvpython.exe')
    if not PVPYTHON.exists():
        import shutil
        found = shutil.which('pvpython')
        if found:
            PVPYTHON = Path(found)
        else:
            print('ERROR: paraview module not found and pvpython.exe not found.')
            print('Run this script with:  pvpython visualize.py')
            sys.exit(1)
    print(f'Relaunching with pvpython: {PVPYTHON}')
    result = subprocess.run([str(PVPYTHON), __file__] + sys.argv[1:])
    sys.exit(result.returncode)

VIZ_DIR    = Path(__file__).resolve().parent
SHOTS_DIR  = VIZ_DIR / 'screenshots'
STATE_FILE = str(VIZ_DIR / 'patch_efield.pvsm')
SHOTS_DIR.mkdir(exist_ok=True)

# ── Helper: load a PVD time series ───────────────────────────────────────────
def load_pvd(name):
    pvd = str(VIZ_DIR / f'{name}.pvd')
    if not os.path.exists(pvd):
        print(f'WARNING: {pvd} not found, skipping')
        return None
    return pv.PVDReader(FileName=pvd)

reader_3d = load_pvd('Et_3D')
reader_xy = load_pvd('Et_xy')
reader_xz = load_pvd('Et_xz')

if reader_3d is None and reader_xy is None:
    print('ERROR: No PVD files found. Run the simulation first.')
    sys.exit(1)

# ── Compute global E-field magnitude range across ALL timesteps ───────────────
print('Computing global E-field range...')
primary = reader_3d or reader_xy
global_max = 0.0
for ts in primary.TimestepValues:
    pv.UpdatePipeline(ts, primary)
    rng = primary.PointData['E-Field'].GetRange(-1)
    if rng[1] > global_max:
        global_max = rng[1]
print(f'  E-field magnitude peak = {global_max:.3e} V/m')
pv.GetAnimationScene().AnimationTime = primary.TimestepValues[0]

# ── Layout ────────────────────────────────────────────────────────────────────
layout = pv.CreateLayout('E-Field Layout')

view3d = pv.CreateRenderView()
pv.AssignViewToLayout(view=view3d, layout=layout, hint=0)
right_loc = layout.SplitViewHorizontal(view3d, 0.5)
view3d.Background = [0.1, 0.1, 0.15]

view_xy = pv.CreateRenderView()
pv.AssignViewToLayout(view=view_xy, layout=layout, hint=right_loc)
bot_loc = layout.SplitViewVertical(view_xy, 0.5)
view_xy.Background = [0.05, 0.05, 0.1]

view_xz = pv.CreateRenderView()
pv.AssignViewToLayout(view=view_xz, layout=layout, hint=bot_loc)
view_xz.Background = [0.05, 0.05, 0.1]

# ── Shared colormap (fixed global range) ─────────────────────────────────────
def setup_colormap(display, view, global_max):
    pv.ColorBy(display, ('POINTS', 'E-Field'))
    lut = pv.GetColorTransferFunction('E-Field')
    lut.ApplyPreset('Rainbow Desaturated', True)
    lut.RescaleTransferFunction(0.0, global_max)
    display.SetScalarBarVisibility(view, True)
    pv.GetScalarBar(lut, view).Title = 'E-Field (V/m)'

# ── 3D view: two crossed slices at the antenna ────────────────────────────────
if reader_3d:
    sl_xy = pv.Slice(Input=reader_3d)
    sl_xy.SliceType = 'Plane'
    sl_xy.SliceType.Normal = [0, 0, 1]
    sl_xy.SliceType.Origin = [0, 0, 1.524]
    d_xy = pv.Show(sl_xy, view3d)
    d_xy.Representation = 'Surface'
    setup_colormap(d_xy, view3d, global_max)

    sl_xz = pv.Slice(Input=reader_3d)
    sl_xz.SliceType = 'Plane'
    sl_xz.SliceType.Normal = [0, 1, 0]
    sl_xz.SliceType.Origin = [0, 0, 0]
    d_xz = pv.Show(sl_xz, view3d)
    d_xz.Representation = 'Surface'
    setup_colormap(d_xz, view3d, global_max)

    view3d.ResetCamera()
    view3d.CameraPosition   = [120, -200, 100]
    view3d.CameraFocalPoint = [0, 0, 5]
    view3d.CameraViewUp     = [0, 0, 1]

# ── XY plane view ─────────────────────────────────────────────────────────────
if reader_xy:
    disp_xy = pv.Show(reader_xy, view_xy)
    disp_xy.Representation = 'Surface'
    setup_colormap(disp_xy, view_xy, global_max)
    view_xy.ResetCamera()
    view_xy.CameraParallelProjection = 1
    view_xy.CameraViewUp   = [0, 1, 0]
    view_xy.CameraPosition = [0, 0, 500]
    view_xy.CameraFocalPoint = [0, 0, 1.524]
    text_xy = pv.Text()
    text_xy.Text = 'XY plane - patch level'
    pv.Show(text_xy, view_xy).FontSize = 10

# ── XZ plane view ─────────────────────────────────────────────────────────────
if reader_xz:
    disp_xz = pv.Show(reader_xz, view_xz)
    disp_xz.Representation = 'Surface'
    setup_colormap(disp_xz, view_xz, global_max)
    view_xz.ResetCamera()
    view_xz.CameraParallelProjection = 1
    view_xz.CameraViewUp   = [0, 0, 1]
    view_xz.CameraPosition = [0, -500, 5]
    view_xz.CameraFocalPoint = [0, 0, 5]
    text_xz = pv.Text()
    text_xz.Text = 'XZ plane - cross-section'
    pv.Show(text_xz, view_xz).FontSize = 10

# ── Animate and save screenshots ──────────────────────────────────────────────
anim = pv.GetAnimationScene()
anim.PlayMode = 'Snap To TimeSteps'
timesteps = list(primary.TimestepValues)
print(f'Saving {len(timesteps)} screenshots to {SHOTS_DIR} ...')
for ts in timesteps:
    anim.AnimationTime = ts
    pv.Render(view3d)
    pv.SaveScreenshot(
        str(SHOTS_DIR / f'Et_t{int(ts):04d}.png'),
        view=view3d,
        ImageResolution=[1200, 900]
    )
print('Screenshots done.')

# ── Build animated GIF from screenshots ──────────────────────────────────────
GIF_FILE = str(SHOTS_DIR.parent / 'efield_animation.gif')
try:
    from PIL import Image
    frames = []
    for ts in timesteps:
        png = SHOTS_DIR / f'Et_t{int(ts):04d}.png'
        if png.exists():
            img = Image.open(str(png))
            w, h = img.size
            frames.append(img.resize((w // 2, h // 2), Image.LANCZOS))
    if frames:
        frames[0].save(
            GIF_FILE,
            save_all=True,
            append_images=frames[1:],
            duration=100,
            loop=0
        )
        print(f'GIF saved: {GIF_FILE}  ({len(frames)} frames)')
    else:
        print('No screenshot frames found for GIF.')
except ImportError:
    print('Pillow not available — skipping GIF export.')

# ── Save ParaView state file (.pvsm) ──────────────────────────────────────────
pv.SaveState(STATE_FILE)
print(f'State saved: {STATE_FILE}')
print(f'To reopen:   paraview --state="{STATE_FILE}"')
